const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 542,
      oldPrice: 553,
      stars: 2,
      userRating: 4,
      promo: 'sale',
      section: 'featured',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 634,
      oldPrice: 745,
      stars: 3,
      promo: 'sale',
      section: 'top seller',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 477,
      oldPrice: 845,
      stars: 1,
      promo: 'sale',
      section: 'sale off',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 457,
      oldPrice: 555,
      stars: 5,
      promo: 'sale',
      section: 'top rated',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 475,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 875,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 587,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 585,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 456,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 345,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 234,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 624,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 624,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 234,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 123,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 153,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 375,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 375,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 345,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 548,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 966,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 574,
      oldPrice: 599,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 474,
      stars: 6,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 345,
      oldPrice: 222,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-1',
      name: 'Chanean Tu Cursus 1',
      category: 'chair',
      price: 90,
      oldPrice: 130,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-2',
      name: 'Chanean Tu Cursus 2',
      category: 'chair',
      price: 70,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-3',
      name: 'Chanean Tu Cursus 3',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-4',
      name: 'Chanean Tu Cursus 4',
      category: 'chair',
      price: 140,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-5',
      name: 'Chanean Tu Cursus 5',
      category: 'chair',
      price: 80,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-6',
      name: 'Chanean Tu Cursus 6',
      category: 'chair',
      price: 160,
      oldPrice: 140,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-7',
      name: 'Chanean Tu Cursus 7',
      category: 'chair',
      price: 220,
      oldPrice: 250,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-8',
      name: 'Chanean Tu Cursus 8',
      category: 'chair',
      price: 90,
      oldPrice: 110,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-9',
      name: 'Chanean Tu Cursus 9',
      category: 'chair',
      price: 150,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-10',
      name: 'Chanean Tu Cursus 10',
      category: 'chair',
      price: 50,
      oldPrice: 60,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-11',
      name: 'Chanean Tu Cursus 11',
      category: 'chair',
      price: 220,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-12',
      name: 'Chanean Tu Cursus 12',
      category: 'chair',
      price: 156,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-13',
      name: 'Chanean Tu Cursus 13',
      category: 'chair',
      price: 54,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-14',
      name: 'Chanean Tu Cursus 14',
      category: 'chair',
      price: 134,
      oldPrice: 232,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-15',
      name: 'Chanean Tu Cursus 15',
      category: 'chair',
      price: 320,
      oldPrice: 310,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'chanean-tu-cursus-16',
      name: 'Chanean Tu Cursus 16',
      category: 'chair',
      price: 412,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-1',
      name: 'Fringilla Et Venatis 1',
      category: 'sofa',
      price: 320,
      oldPrice: 440,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-2',
      name: 'Fringilla Et Venatis 2',
      category: 'sofa',
      price: 330,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-3',
      name: 'Fringilla Et Venatis 3',
      category: 'sofa',
      price: 553,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-4',
      name: 'Fringilla Et Venatis 4',
      category: 'sofa',
      price: 330,
      oldPrice: 320,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-5',
      name: 'Fringilla Et Venatis 5',
      category: 'sofa',
      price: 120,
      oldPrice: 200,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-6',
      name: 'Fringilla Et Venatis 6',
      category: 'sofa',
      price: 300,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-7',
      name: 'Fringilla Et Venatis 7',
      category: 'sofa',
      price: 320,
      oldPrice: 440,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'fringilla-et-venatis-8',
      name: 'Fringilla Et Venatis 8',
      category: 'sofa',
      price: 110,
      oldPrice: 120,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-1',
      name: 'Enim Da Pellentes 1',
      category: 'table',
      price: 110,
      oldPrice: 120,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-2',
      name: 'Enim Da Pellentes 2',
      category: 'table',
      price: 230,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-3',
      name: 'Enim Da Pellentes 3',
      category: 'table',
      price: 120,
      oldPrice: 145,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-4',
      name: 'Enim Da Pellentes 4',
      category: 'table',
      price: 50,
      oldPrice: 70,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-5',
      name: 'Enim Da Pellentes 5',
      category: 'table',
      price: 200,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-6',
      name: 'Enim Da Pellentes 6',
      category: 'table',
      price: 10,
      oldPrice: 50,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-7',
      name: 'Enim Da Pellentes 7',
      category: 'table',
      price: 80,
      oldPrice: 90,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-8',
      name: 'Enim Da Pellentes 8',
      category: 'table',
      price: 56,
      oldPrice: 50,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-9',
      name: 'Enim Da Pellentes 9',
      category: 'table',
      price: 160,
      oldPrice: 180,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-10',
      name: 'Enim Da Pellentes 10',
      category: 'table',
      price: 90,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-11',
      name: 'Enim Da Pellentes 11',
      category: 'table',
      price: 110,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-12',
      name: 'Enim Da Pellentes 12',
      category: 'table',
      price: 150,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-13',
      name: 'Enim Da Pellentes 13',
      category: 'table',
      price: 100,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-14',
      name: 'Enim Da Pellentes 14',
      category: 'table',
      price: 70,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-15',
      name: 'Enim Da Pellentes 15',
      category: 'table',
      price: 110,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'enim-da-pellentes-16',
      name: 'Enim Da Pellentes 16',
      category: 'table',
      price: 177,
      oldPrice: 170,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-1',
      name: 'Pulvinar Et Vulputate 1',
      category: 'dining',
      price: 1774,
      oldPrice: 1700,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-2',
      name: 'Pulvinar Et Vulputate 2',
      category: 'dining',
      price: 3234,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-3',
      name: 'Pulvinar Et Vulputate 3',
      category: 'dining',
      price: 1123,
      oldPrice: 1100,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-4',
      name: 'Pulvinar Et Vulputate 4',
      category: 'dining',
      price: 2345,
      oldPrice: 1700,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-5',
      name: 'Pulvinar Et Vulputate 5',
      category: 'dining',
      price: 1243,
      oldPrice: 1233,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-6',
      name: 'Pulvinar Et Vulputate 6',
      category: 'dining',
      price: 1543,
      oldPrice: 2230,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-7',
      name: 'Pulvinar Et Vulputate 7',
      category: 'dining',
      price: 9824,
      oldPrice: 9000,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-8',
      name: 'Pulvinar Et Vulputate 8',
      category: 'dining',
      price: 6544,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-9',
      name: 'Pulvinar Et Vulputate 9',
      category: 'dining',
      price: 2000,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-10',
      name: 'Pulvinar Et Vulputate 10',
      category: 'dining',
      price: 1100,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-11',
      name: 'Pulvinar Et Vulputate 11',
      category: 'dining',
      price: 2020,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-12',
      name: 'Pulvinar Et Vulputate 12',
      category: 'dining',
      price: 1770,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-13',
      name: 'Pulvinar Et Vulputate 13',
      category: 'dining',
      price: 6754,
      oldPrice: 4530,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-14',
      name: 'Pulvinar Et Vulputate 14',
      category: 'dining',
      price: 3000,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-15',
      name: 'Pulvinar Et Vulputate 15',
      category: 'dining',
      price: 2300,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
    {
      id: 'pulvinar-et-vulputate-16',
      name: 'Pulvinar Et Vulputate 16',
      category: 'dining',
      price: 4550,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: false,
    },
  ],
  cart: {
    products: [],
  },
  brands: [
    { id: 1, name: 'Adidas', logo: 'AdidasLogo' },
    { id: 2, name: 'Microsoft', logo: 'MicrosoftLogo' },
    { id: 3, name: 'Audi', logo: 'AudiLogo' },
    { id: 4, name: 'Batman', logo: 'BatmanLogo' },
    { id: 5, name: 'Jewellery', logo: 'JewelleryLogo' },
    { id: 6, name: 'Volvo', logo: 'VolvoLogo' },
    { id: 8, name: 'Fantail', logo: 'FantailLogo' },
    { id: 9, name: 'Flyingcarpet', logo: 'FlyingcarpetLogo' },
    { id: 10, name: 'Home', logo: 'HomeLogo' },
    { id: 11, name: 'Opel', logo: 'OpelLogo' },
  ],
  feedbacks: [
    {
      id: '1',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, autem cupiditate ea necessitatibus. Eaque enim sit architecto atque possimus non asperiores rem nesciunt voluptate voluptatem, quia quibusdam magnam, sequi sapiente!',
      author: 'John Smith',
      description: 'Furniture client',
    },
    {
      id: '2',
      text:
        'Eaque enim sit architecto atque possimus non asperiores rem nesciunt voluptate voluptatem, quia quibusdam magnam, sequi sapiente!',
      author: 'Jane Doe',
      description: 'Furniture client',
    },
    {
      id: '3',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, autem cupiditate ea necessitatibus.',
      author: 'Dexter Owens',
      description: 'Furniture client',
    },
  ],
  newsletter: ['test@test.pl', 'admin@admin.pl', '1@1.pl', '0@0.pl'],

  blog: [
    {
      id: '1',
      image: 'https://images.pexels.com/photos/3653849/pexels-photo-3653849.jpeg',
      date: '12-02-2023',
      comments: '4',
      title: 'Article 1',
      text:
        'Aliquam dictum pellentesque nibh sit amet dapibus. Vivamus eget luctus nisi. Nullam euismod leo vehicula, rutrum magna in, ornare enim vehicula, rutrum magna in, ornare enim.',
    },
    {
      id: '2',
      image: 'https://images.pexels.com/photos/16474101/pexels-photo-16474101.jpeg',
      date: '01-12-2022',
      comments: '14',
      title: 'Article 2',
      text:
        'Aliquam dictum pellentesque nibh sit amet dapibus. Vivamus eget luctus nisi. Nullam euismod leo vehicula, rutrum magna in, ornare enim vehicula, rutrum magna in, ornare enim.',
    },
    {
      id: '3',
      image: 'https://images.pexels.com/photos/14765970/pexels-photo-14765970.jpeg',
      date: '30-04-2023',
      comments: '7',
      title: 'Article 3',
      text:
        'Aliquam dictum pellentesque nibh sit amet dapibus. Vivamus eget luctus nisi. Nullam euismod leo vehicula, rutrum magna in, ornare enim vehicula, rutrum magna in, ornare enim.',
    },
  ],
};

export default initialState;
